# Generated by Django 3.2.3 on 2021-06-06 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_auto_20210606_2002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_image',
            field=models.ImageField(default='', upload_to='upload/product_img'),
        ),
    ]
