# Generated by Django 3.2.3 on 2021-06-07 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_dec',
            field=models.TextField(max_length=500),
        ),
    ]
