# Generated by Django 3.2.3 on 2021-06-08 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0005_alter_product_product_dec'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=100)),
                ('user_contact', models.CharField(max_length=100)),
                ('user_email', models.CharField(max_length=100)),
                ('user_msg', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='category',
        ),
    ]
