# Generated by Django 3.2.3 on 2021-06-08 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0009_checkout_product_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Oders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Product_name', models.CharField(default='', max_length=100)),
                ('name', models.CharField(default='', max_length=100)),
                ('phone', models.CharField(default='', max_length=100)),
                ('email', models.CharField(default='', max_length=100)),
                ('address', models.TextField(default='', max_length=500)),
                ('country', models.CharField(default='', max_length=100)),
                ('Product_price', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='Checkout',
        ),
    ]
