# Generated by Django 3.2.3 on 2021-06-08 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0010_auto_20210609_0000'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Oders',
            new_name='Order',
        ),
    ]
