# Generated by Django 3.2.3 on 2021-06-08 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0011_rename_oders_order'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='Product_name',
            new_name='price',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='Product_price',
            new_name='product',
        ),
    ]
