# Generated by Django 3.2.3 on 2021-06-08 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0012_auto_20210609_0021'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='product',
            new_name='order_product',
        ),
    ]
